import click
import os
from .utils import (create_project_folder, 
                    check_or_create_config, 
                    navigate) 
from subprocess import Popen


@click.command()
@click.argument("project_name", nargs=1, required=True)
@click.option("--python", "python", help="Python Project", is_flag=True)
@click.option("--nodejs", "nodejs", help="NodeJS Project", is_flag=True)
def create_project(project_name, python, nodejs):
    projects_folder_path = check_or_create_config()
    click.echo('projects_folder_path: {}'.format(projects_folder_path))
    path = navigate(projects_folder_path)
    if os.path.exists(os.path.join(path, project_name)):
        print('Folder with the same name already exists')
        return
    os.system('mkdir ' + path + '/' + project_name)

    if python:
        create_python_project(project_name, path)
    elif nodejs:
        create_nodejs_project(project_name, path)
    else:
        click.echo('No Project Type Selected')
        return


def create_python_project(project_name, project_path):
    print('Creating Python Project...')
    with open (os.path.join(project_path, project_name, '__init__.py'), 'w') as f:
        f.write('# This file is generated By Eclip!!!\n')
        f.write('# Write your code here...\n')
    with open (os.path.join(project_path, project_name, 'main.py'), 'w') as f:
        f.write('# This file is generated By Eclip!!!\n')
        f.write('# Write your code here...\n')
    print('Project Created...')
    print('Navigate to the path to start coding: ' + os.path.join(project_path, project_name))
       
    

def create_nodejs_project(project_name, path):
    print('Creating NodeJS Project...')
    with open (os.path.join(path, project_name, 'package.json'), 'w') as f:
        f.write("""{
  "name": "aaa8",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \\"Error: no test specified\\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}""")
    with open (os.path.join(path, project_name, 'index.js'), 'w') as f:
        f.write("""// This file is generated By Eclip!!!\n// Write your code here...\n""")
        
